runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /manifest.webmanifest
  static_files: manifest.webmanifest
  upload: manifest.webmanifest

- url: /share.html
  static_files: share.html
  upload: share.html

- url: /share-polyfill.js
  static_files: share-polyfill.js
  upload: share-polyfill.js

- url: /share-target-destination.html
  script: share-target-destination.app

- url: /share-target-destination.client.html
  static_files: share-target-destination.client.html
  upload: share-target-destination.client.html

- url: /share-target-polyfill.js
  static_files: share-target-polyfill.js
  upload: share-target-polyfill.js

- url: /sw.js
  static_files: sw.js
  upload: sw.js

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
